### ISSUE TITLE
[BUG][SLIM6] SIM switch on/off in SiM Settings doesnt work.

### ISSUE THREAD

**Issue by skinzor** [SlimRoms/packages_apps_Settings#34]
Hi there!
An user which has a dual sim phone model has reported that the SIM switch from SIM Settings is not working.

He took following logcat: http://pastebin.com/T0EHJHva .

E SimEnablerPreference(1): Failed to get pref, slotId: 1 Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int com.android.internal.telephony.IExtTelephony.getCurrentUiccCardProvisioningStatus(int)' on a null object reference

I have searched about that SimEnablerPreference error which you can see in the logcat and found some XDA threads (one of them is SlimROM) with same problem and the developer said in his thread that he fixed it.

I have took his whole Sim Settings java files, but unfortunately i ran into build error. I took these ones: https://github.com/Martinusbe/packages_apps_Settings/tree/mm/src/com/android/settings/sim .

Does someone have any tips?

@YAJATapps : Im sorry for mentioning you, but perhaps you can help me with this one too?

Thank you!

**Comment by YAJATapps** [comment]
I have not tested but I think  it is fixed .
Firstly you should try compiling with latest slimrom 6 only and if error persist then try anything else.
That user might have not used latest slimrom 6.

**Comment by skinzor** [comment]
Well, i compiled latest one and the user had that build (it was first build).
I kinda canceled working on it since it is good as it is and since i wanna build other rom.

Anyway, thank you for your reply and time!


PS: shall i let the issue opened?

**Comment by YAJATapps** [comment]
Then i don't know the fix
You can close it since you are not working on it.
