### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SvtDon** [SlimRoms/packages_apps_Settings#9]
Issue recently with keyboard covering up color picker when you select the color code on the left to change manually. Happened around the navbar button and transparency I noticed when i did a cherry pick and tested yours too. Figured i would let ya guys know before next release

**Comment by kufikugel** [comment]
hi,

oh yeah thanks...I see.....this we have on all color picker places lol. Must check what to do.

**Comment by SvtDon** [comment]
Thanks buddy. I think I got that already the updated ram later on mixed in with another one of the sloppy pushes. Would have tried and find a fix for your color picker. My desktop just took a shit on my Linux loosing everything I had before I pushed NY manifest again to sync my source Lol. Sucks...

**Comment by kufikugel** [comment]
np...I have to say thanks. May be I have overseen the commit lol....5 am
here and totally tired. lol

if you want try to add android:windowSoftInputMode="adjustResize" in
settings androidmanifest

not sure if this works but a fast try. I must sleep now lol.....will look
into it tomorrow and will inform you.

cheer and good night and be nice to your desktop ;)

2013/2/1 NexusEvolution notifications@github.com

**Comment by kufikugel** [comment]
lol me again...check here

adjustpan should be right. adjustresize I think there is no space on
colorpicker for resizing.....so it must be pushed up then. Adjustpan should
do it

so now really out to bed lol

night

2013/2/1 Lars Greiss kufikugel@googlemail.com

**Comment by kufikugel** [comment]
http://developer.android.com/guide/topics/manifest/activity-element.html#wsoft

check here I ment the forgotten link lmao

2013/2/1 Lars Greiss kufikugel@googlemail.com

**Comment by SvtDon** [comment]
Thanks man. Yea pretty late over there Lol. Night!
